### ISSUE TITLE
Update slides 

### ISSUE THREAD

**Issue by lyashevska** [esciencecenter-digital-skills/good-practices-in-research-software-development#27]
- [x] Fix [colours](https://lyashevska.github.io/ds-cr-slides/good_practices/#/0/3 )
- [ ] esciencecenter-digital-skills/good-practices-lesson#14
- [ ] esciencecenter-digital-skills/good-practices-lesson#15
- [ ] Improve modular code section @DaniBodor 
- [ ] esciencecenter-digital-skills/good-practices-lesson#9 @carlosug

**Comment by lyashevska** [comment]
This is the most recent version https://github.com/lyashevska/ds-cr-slides
