### ISSUE TITLE
Move content of the workshop

### ISSUE THREAD

**Issue by lyashevska** [esciencecenter-digital-skills/good-practices-in-research-software-development#33]
- [ ] esciencecenter-digital-skills/git-lesson#22
- [ ] esciencecenter-digital-skills/good-practices-lesson#18
- [x] esciencecenter-digital-skills/good-practices-in-research-software-development#36
- [x] esciencecenter-digital-skills/good-practices-in-research-software-development#37
- [x] esciencecenter-digital-skills/good-practices-in-research-software-development#38
- [x] esciencecenter-digital-skills/good-practices-in-research-software-development#39
- [x] esciencecenter-digital-skills/good-practices-in-research-software-development#40
- [x] esciencecenter-digital-skills/good-practices-in-research-software-development#41
